### ISSUE TITLE
Not all inputs are transferred to simulation

### ISSUE THREAD

**Issue by fkuschel** [ZBT-Tools/pemfc-dash-app#12]
Example: 
Multinputs under "Physical Properties"->

![image](https://user-images.githubusercontent.com/94350939/209134239-43c04dfc-56af-4e2a-83d0-ebd40104de80.png)

Debugging:

Inside first "Run Simulation" Button Callback:
dash_functions.process_inputs() collects values properly. Thats why also "save results" and "load results" works fine.
![image](https://user-images.githubusercontent.com/94350939/209134573-17ee500d-91c9-45bb-a986-1c5f0abe5366.png)

Inside next Callback "run_simulation()"
data_transfer.gui_to_sim_transfer(input_data, settings) creates settings-dict for calculation. 
Default-values from local settings file are not overwritten. 
![image](https://user-images.githubusercontent.com/94350939/209135463-73fcb9f0-c79e-44b5-9403-77f9eb0e2fdb.png)

I'm looking into it.

**Comment by fkuschel** [comment]
Some details:

1. Issue: 
  Naming deviation:
  Dash App: ['anode', 'electrical_conductivity_gde']
  GUI App: ['anode','gde', 'electric_conductivity'] 
    **--> Needs to be fixed in Dash app**

2. Issue:
   pemfc_gui.data_transfer.gui_to_sim_transfer() should be improved
   - give warning, if not all fields are updated.
   - do not allow creation of new entries by gui. 
  **--> Open separate issue in pemfc_gui**
   
![image](https://user-images.githubusercontent.com/94350939/209140180-9386be94-98d2-462e-9ebd-72f2417de1c2.png)

**Comment by fkuschel** [comment]
![image](https://user-images.githubusercontent.com/94350939/209143250-71642453-d079-4f43-82ce-74e2b9c7ea16.png)

**Comment by fkuschel** [comment]
Definition in gui tabs
![image](https://user-images.githubusercontent.com/94350939/209143907-91db4471-5bc6-4751-8f59-b1d564fa90d4.png)

**Comment by lufire** [comment]
solved in last PR
