### ISSUE TITLE
df_result_data_store on server side

### ISSUE THREAD

**Issue by lufire** [ZBT-Tools/pemfc-dash-app#33]
Right now df_result_data_store is cached in a normal dcc.Store element, meaning in the clients browser. To cache it on the server I introduced the ServersideOutput Store element for the previous result_data_store. Right now I think it makes sense to also save the df_result_data_store in a ServersideOutput class to allow for redis storage. What do you think?

**Comment by fkuschel** [comment]
Agree! 
I used normal dcc.Store elements for no speacial reason.

**Comment by fkuschel** [comment]
Resolved by Pullrequest #37
