### ISSUE TITLE
checkboxes are  not updated by settings.json input

### ISSUE THREAD

**Issue by lufire** [ZBT-Tools/pemfc-dash-app#34]
Checkbox vizualization (checked or unchecked) does not correspond to "settings.json" loading either on initialization or after loading a custom settings file. It does work on the old version: www.fuel-cell-model.com

**Comment by fkuschel** [comment]
Some rework needs to be done.
Bug can be fixed as discussed, see attached branch. 

Additionally, I quickly fixed the following:

Issue:
- Input fields are generated and **initialized** by pemfc-gui input dicts, but should be initialized with pemfc settings.json

Quickfix:
- Input fields are updated by pemfc default settings.json values inside initialization callback function

However, a rework of the initialization process should be done, including rework of dash_functions.parse_contents.
